// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsXzDWBdz-lOca7AYnU4fy4FO2wR5OpnY',
    appId: '1:33985731065:web:9d01e1ba25d23704aa8528',
    messagingSenderId: '33985731065',
    projectId: 'aut-toolkit',
    authDomain: 'aut-toolkit.firebaseapp.com',
    storageBucket: 'aut-toolkit.firebasestorage.app',
    measurementId: 'G-3VB9VECK7G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIWNm6LStkUmckj2pR8_3OIMWwXxDgBo4',
    appId: '1:33985731065:android:728a97736c321293aa8528',
    messagingSenderId: '33985731065',
    projectId: 'aut-toolkit',
    storageBucket: 'aut-toolkit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRtzSSiVf3VLiq9aNCZ0HpclHfM9EO5tk',
    appId: '1:33985731065:ios:c94b08a4490a82beaa8528',
    messagingSenderId: '33985731065',
    projectId: 'aut-toolkit',
    storageBucket: 'aut-toolkit.firebasestorage.app',
    iosBundleId: 'sk.krib.autToolkit',
  );
}
