// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'features/card_management/data/model/user_card_entity.dart';
import 'features/challenging_behaviour/data/model/challenging_behaviour_diary_entry_entity.dart';
import 'features/challenging_behaviour/data/model/challenging_behaviour_entity.dart';
import 'features/eating_habits/data/model/eating_habit_entity.dart';
import 'features/good_habits/data/model/good_habit_entity.dart';
import 'features/selected_person/data/model/selected_person_entity.dart';
import 'features/visual_supports/first_then_board/data/model/first_then_board_entity.dart';
import 'features/visual_supports/visual_lists/data/model/visual_list_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 139465113525671056),
    name: 'ChallengingBehaviourDiaryEntryEntity',
    lastPropertyId: const obx_int.IdUid(9, 8473330541405588167),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3276799885575513242),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1996232934584247842),
        name: 'challengingBehaviourId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(1, 7265063553320486894),
        relationTarget: 'ChallengingBehaviourEntity',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3810550962242010286),
        name: 'location',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4327789277245649275),
        name: 'date',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2257877021023419224),
        name: 'duration',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5067823526267149243),
        name: 'circumstances',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 6317075041900276104),
        name: 'people',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 9114528613422825857),
        name: 'outcome',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 8473330541405588167),
        name: 'reflection',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 6231389929878358286),
    name: 'ChallengingBehaviourEntity',
    lastPropertyId: const obx_int.IdUid(12, 8991946706523787109),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 957492046697605941),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3447244676382177609),
        name: 'occuring',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8814747557842586450),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 9102207563706588597),
        name: 'from',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1746883064538615473),
        name: 'generalDescription',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 3653867454443783666),
        name: 'userId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 3086927186571094073),
        name: 'selectedPersonId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 7266084622565627497),
        name: 'remoteId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 8464017446173604607),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 2092839996886774045),
        name: 'isSynced',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 284106223907391829),
        name: 'pendingAction',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 8991946706523787109),
        name: 'isDeleted',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'diaryEntries',
        srcEntity: 'ChallengingBehaviourDiaryEntryEntity',
        srcField: '',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 1812295606420934787),
    name: 'EatingHabitEntity',
    lastPropertyId: const obx_int.IdUid(15, 3150947832643554549),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6931242426439301705),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8423343766618127990),
        name: 'to',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6790623775884093556),
        name: 'isEatingFlag',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2624360315488368124),
        name: 'from',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8315437001960652234),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 7309644610374706293),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 2753014414256372943),
        name: 'userId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 5857236163708609311),
        name: 'selectedPersonId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 8780796419473162185),
        name: 'imageFilePath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 8541197116252804647),
        name: 'remoteId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 3953686466508685437),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 3883763254183442183),
        name: 'isSynced',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 2004123583268734160),
        name: 'pendingAction',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 9218695170647944606),
        name: 'isDeleted',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 3150947832643554549),
        name: 'remoteImgPath',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(6, 4139673972050310461),
    name: 'GoodHabitEntity',
    lastPropertyId: const obx_int.IdUid(13, 2483097477496792416),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6926905718660631014),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5210479876626957908),
        name: 'from',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2843212185898592918),
        name: 'userId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1556262315733938184),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5234794128667873739),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6350548586302974283),
        name: 'isOccuringFlag',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 3174147389341847264),
        name: 'selectedPersonId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 32978948303884726),
        name: 'to',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 7398368198971547297),
        name: 'remoteId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 3180266639006987475),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 1501606961408542208),
        name: 'isSynced',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 8929463395114452926),
        name: 'pendingAction',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 2483097477496792416),
        name: 'isDeleted',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(7, 6805867481002173015),
    name: 'SelectedPersonEntity',
    lastPropertyId: const obx_int.IdUid(9, 1312882274832971233),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5608958196129389297),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2353551128508159732),
        name: 'isSelected',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2836334951276873748),
        name: 'userId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4538225831951454339),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 906012178411674136),
        name: 'remoteId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 8506682528747091890),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 2635370223566698696),
        name: 'isSynced',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 6625574527690844553),
        name: 'pendingAction',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 1312882274832971233),
        name: 'isDeleted',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(9, 6961689238950263914),
    name: 'UserCardEntity',
    lastPropertyId: const obx_int.IdUid(12, 1866969144154095752),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2788912893503672152),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7938595103906609350),
        name: 'arasaacId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 9165398644864101908),
        name: 'userId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 316787185739682720),
        name: 'localImgPath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6103644701031938418),
        name: 'namesJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5505214374322437866),
        name: 'remoteId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1398351388652578857),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 2437854286005673038),
        name: 'isSynced',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 9095108670282445750),
        name: 'pendingAction',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 3224521116130135316),
        name: 'isDeleted',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 7584242058812361914),
        name: 'remoteImgPath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 1866969144154095752),
        name: 'wordCategory',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(10, 1199814977235704664),
    name: 'FirstThenBoardEntity',
    lastPropertyId: const obx_int.IdUid(5, 6697845778278102898),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8618796915687496532),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3596057190440106154),
        name: 'userId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7580350952719720507),
        name: 'firstId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(2, 9087415955429520808),
        relationTarget: 'UserCardEntity',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3226230904224083014),
        name: 'thenId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(3, 3602341172251329567),
        relationTarget: 'UserCardEntity',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6697845778278102898),
        name: 'name',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(11, 7067190488023369742),
    name: 'VisualListEntity',
    lastPropertyId: const obx_int.IdUid(6, 1529333965761639297),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1089364678232753148),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7996671573816971021),
        name: 'userId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4605483790459533064),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8145002004210313983),
        name: 'isVisualSchedule',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5735948704890917363),
        name: 'isVisualDiagram',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1529333965761639297),
        name: 'stepsOrderJson',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[
      obx_int.ModelRelation(
        id: const obx_int.IdUid(1, 3447432801872670905),
        name: 'steps',
        targetId: const obx_int.IdUid(9, 6961689238950263914),
      ),
    ],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(11, 7067190488023369742),
    lastIndexId: const obx_int.IdUid(3, 3602341172251329567),
    lastRelationId: const obx_int.IdUid(1, 3447432801872670905),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [
      1777307641083598478,
      6112168635049409585,
      8990935288411066217,
    ],
    retiredIndexUids: const [],
    retiredPropertyUids: const [
      591679213236383350,
      7323305404545168403,
      1219579721037450855,
      593779817146309026,
      1176311604953178663,
      3518344782468400788,
      4393786231541083778,
      4128286833958398028,
      5353683167311258387,
      69716348719230726,
      1233996314118088075,
      6645588857862198462,
      938737596790947008,
      8520208140183450181,
      4563356993705894073,
      25719061704574666,
      6097620739564343198,
      2821425816074388931,
      4317918244815278053,
    ],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    ChallengingBehaviourDiaryEntryEntity:
        obx_int.EntityDefinition<ChallengingBehaviourDiaryEntryEntity>(
          model: _entities[0],
          toOneRelations: (ChallengingBehaviourDiaryEntryEntity object) => [
            object.challengingBehaviour,
          ],
          toManyRelations: (ChallengingBehaviourDiaryEntryEntity object) => {},
          getId: (ChallengingBehaviourDiaryEntryEntity object) => object.id,
          setId: (ChallengingBehaviourDiaryEntryEntity object, int id) {
            object.id = id;
          },
          objectToFB:
              (ChallengingBehaviourDiaryEntryEntity object, fb.Builder fbb) {
                final locationOffset = fbb.writeString(object.location);
                final circumstancesOffset = fbb.writeString(
                  object.circumstances,
                );
                final peopleOffset = fbb.writeList(
                  object.people.map(fbb.writeString).toList(growable: false),
                );
                final outcomeOffset = fbb.writeString(object.outcome);
                final reflectionOffset = fbb.writeString(object.reflection);
                fbb.startTable(10);
                fbb.addInt64(0, object.id ?? 0);
                fbb.addInt64(1, object.challengingBehaviour.targetId);
                fbb.addOffset(2, locationOffset);
                fbb.addInt64(3, object.date.millisecondsSinceEpoch);
                fbb.addInt64(4, object.duration);
                fbb.addOffset(5, circumstancesOffset);
                fbb.addOffset(6, peopleOffset);
                fbb.addOffset(7, outcomeOffset);
                fbb.addOffset(8, reflectionOffset);
                fbb.finish(fbb.endTable());
                return object.id ?? 0;
              },
          objectFromFB: (obx.Store store, ByteData fbData) {
            final buffer = fb.BufferContext(fbData);
            final rootOffset = buffer.derefObject(0);
            final idParam = const fb.Int64Reader().vTableGetNullable(
              buffer,
              rootOffset,
              4,
            );
            final locationParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGet(buffer, rootOffset, 8, '');
            final dateParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
            );
            final durationParam = const fb.Int64Reader().vTableGet(
              buffer,
              rootOffset,
              12,
              0,
            );
            final circumstancesParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGet(buffer, rootOffset, 14, '');
            final peopleParam = const fb.ListReader<String>(
              fb.StringReader(asciiOptimization: true),
              lazy: false,
            ).vTableGet(buffer, rootOffset, 16, []);
            final outcomeParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGet(buffer, rootOffset, 18, '');
            final reflectionParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGet(buffer, rootOffset, 20, '');
            final object = ChallengingBehaviourDiaryEntryEntity(
              id: idParam,
              location: locationParam,
              date: dateParam,
              duration: durationParam,
              circumstances: circumstancesParam,
              people: peopleParam,
              outcome: outcomeParam,
              reflection: reflectionParam,
            );
            object.challengingBehaviour.targetId = const fb.Int64Reader()
                .vTableGet(buffer, rootOffset, 6, 0);
            object.challengingBehaviour.attach(store);
            return object;
          },
        ),
    ChallengingBehaviourEntity:
        obx_int.EntityDefinition<ChallengingBehaviourEntity>(
          model: _entities[1],
          toOneRelations: (ChallengingBehaviourEntity object) => [],
          toManyRelations: (ChallengingBehaviourEntity object) => {
            obx_int.RelInfo<ChallengingBehaviourDiaryEntryEntity>.toOneBacklink(
              2,
              object.id!,
              (ChallengingBehaviourDiaryEntryEntity srcObject) =>
                  srcObject.challengingBehaviour,
            ): object.diaryEntries,
          },
          getId: (ChallengingBehaviourEntity object) => object.id,
          setId: (ChallengingBehaviourEntity object, int id) {
            object.id = id;
          },
          objectToFB: (ChallengingBehaviourEntity object, fb.Builder fbb) {
            final nameOffset = fbb.writeString(object.name);
            final generalDescriptionOffset = fbb.writeString(
              object.generalDescription,
            );
            final userIdOffset = fbb.writeString(object.userId);
            final remoteIdOffset = object.remoteId == null
                ? null
                : fbb.writeString(object.remoteId!);
            fbb.startTable(13);
            fbb.addInt64(0, object.id ?? 0);
            fbb.addBool(1, object.occuring);
            fbb.addOffset(2, nameOffset);
            fbb.addInt64(3, object.from.millisecondsSinceEpoch);
            fbb.addOffset(4, generalDescriptionOffset);
            fbb.addOffset(5, userIdOffset);
            fbb.addInt64(6, object.selectedPersonId);
            fbb.addOffset(7, remoteIdOffset);
            fbb.addInt64(8, object.updatedAt.millisecondsSinceEpoch);
            fbb.addBool(9, object.isSynced);
            fbb.addInt64(10, object.pendingAction);
            fbb.addBool(11, object.isDeleted);
            fbb.finish(fbb.endTable());
            return object.id ?? 0;
          },
          objectFromFB: (obx.Store store, ByteData fbData) {
            final buffer = fb.BufferContext(fbData);
            final rootOffset = buffer.derefObject(0);
            final idParam = const fb.Int64Reader().vTableGetNullable(
              buffer,
              rootOffset,
              4,
            );
            final nameParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGet(buffer, rootOffset, 8, '');
            final fromParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
            );
            final generalDescriptionParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGet(buffer, rootOffset, 12, '');
            final diaryEntriesParam =
                obx.ToMany<ChallengingBehaviourDiaryEntryEntity>();
            final occuringParam = const fb.BoolReader().vTableGet(
              buffer,
              rootOffset,
              6,
              false,
            );
            final userIdParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGet(buffer, rootOffset, 14, '');
            final selectedPersonIdParam = const fb.Int64Reader().vTableGet(
              buffer,
              rootOffset,
              16,
              0,
            );
            final remoteIdParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGetNullable(buffer, rootOffset, 18);
            final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0),
            );
            final isSyncedParam = const fb.BoolReader().vTableGet(
              buffer,
              rootOffset,
              22,
              false,
            );
            final isDeletedParam = const fb.BoolReader().vTableGet(
              buffer,
              rootOffset,
              26,
              false,
            );
            final pendingActionParam = const fb.Int64Reader().vTableGet(
              buffer,
              rootOffset,
              24,
              0,
            );
            final object = ChallengingBehaviourEntity(
              id: idParam,
              name: nameParam,
              from: fromParam,
              generalDescription: generalDescriptionParam,
              diaryEntries: diaryEntriesParam,
              occuring: occuringParam,
              userId: userIdParam,
              selectedPersonId: selectedPersonIdParam,
              remoteId: remoteIdParam,
              updatedAt: updatedAtParam,
              isSynced: isSyncedParam,
              isDeleted: isDeletedParam,
              pendingAction: pendingActionParam,
            );
            obx_int.InternalToManyAccess.setRelInfo<ChallengingBehaviourEntity>(
              object.diaryEntries,
              store,
              obx_int.RelInfo<
                ChallengingBehaviourDiaryEntryEntity
              >.toOneBacklink(
                2,
                object.id!,
                (ChallengingBehaviourDiaryEntryEntity srcObject) =>
                    srcObject.challengingBehaviour,
              ),
            );
            return object;
          },
        ),
    EatingHabitEntity: obx_int.EntityDefinition<EatingHabitEntity>(
      model: _entities[2],
      toOneRelations: (EatingHabitEntity object) => [],
      toManyRelations: (EatingHabitEntity object) => {},
      getId: (EatingHabitEntity object) => object.id,
      setId: (EatingHabitEntity object, int id) {
        object.id = id;
      },
      objectToFB: (EatingHabitEntity object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final descriptionOffset = fbb.writeString(object.description);
        final userIdOffset = fbb.writeString(object.userId);
        final imageFilePathOffset = object.imageFilePath == null
            ? null
            : fbb.writeString(object.imageFilePath!);
        final remoteIdOffset = object.remoteId == null
            ? null
            : fbb.writeString(object.remoteId!);
        final remoteImgPathOffset = object.remoteImgPath == null
            ? null
            : fbb.writeString(object.remoteImgPath!);
        fbb.startTable(16);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.to?.millisecondsSinceEpoch);
        fbb.addBool(2, object.isEatingFlag);
        fbb.addInt64(3, object.from.millisecondsSinceEpoch);
        fbb.addOffset(4, nameOffset);
        fbb.addOffset(5, descriptionOffset);
        fbb.addOffset(6, userIdOffset);
        fbb.addInt64(7, object.selectedPersonId);
        fbb.addOffset(8, imageFilePathOffset);
        fbb.addOffset(9, remoteIdOffset);
        fbb.addInt64(10, object.updatedAt.millisecondsSinceEpoch);
        fbb.addBool(11, object.isSynced);
        fbb.addInt64(12, object.pendingAction);
        fbb.addBool(13, object.isDeleted);
        fbb.addOffset(14, remoteImgPathOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final toValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          6,
        );
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final fromParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final toParam = toValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(toValue);
        final isEatingFlagParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          8,
          false,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final userIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final selectedPersonIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final imageFilePathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final remoteIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 22);
        final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 24, 0),
        );
        final isSyncedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          26,
          false,
        );
        final isDeletedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          30,
          false,
        );
        final pendingActionParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          28,
          0,
        );
        final remoteImgPathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 32);
        final object = EatingHabitEntity(
          id: idParam,
          from: fromParam,
          to: toParam,
          isEatingFlag: isEatingFlagParam,
          name: nameParam,
          description: descriptionParam,
          userId: userIdParam,
          selectedPersonId: selectedPersonIdParam,
          imageFilePath: imageFilePathParam,
          remoteId: remoteIdParam,
          updatedAt: updatedAtParam,
          isSynced: isSyncedParam,
          isDeleted: isDeletedParam,
          pendingAction: pendingActionParam,
          remoteImgPath: remoteImgPathParam,
        );

        return object;
      },
    ),
    GoodHabitEntity: obx_int.EntityDefinition<GoodHabitEntity>(
      model: _entities[3],
      toOneRelations: (GoodHabitEntity object) => [],
      toManyRelations: (GoodHabitEntity object) => {},
      getId: (GoodHabitEntity object) => object.id,
      setId: (GoodHabitEntity object, int id) {
        object.id = id;
      },
      objectToFB: (GoodHabitEntity object, fb.Builder fbb) {
        final userIdOffset = fbb.writeString(object.userId);
        final nameOffset = fbb.writeString(object.name);
        final descriptionOffset = fbb.writeString(object.description);
        final remoteIdOffset = object.remoteId == null
            ? null
            : fbb.writeString(object.remoteId!);
        fbb.startTable(14);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.from.millisecondsSinceEpoch);
        fbb.addOffset(2, userIdOffset);
        fbb.addOffset(3, nameOffset);
        fbb.addOffset(4, descriptionOffset);
        fbb.addBool(5, object.isOccuringFlag);
        fbb.addInt64(6, object.selectedPersonId);
        fbb.addInt64(7, object.to?.millisecondsSinceEpoch);
        fbb.addOffset(8, remoteIdOffset);
        fbb.addInt64(9, object.updatedAt.millisecondsSinceEpoch);
        fbb.addBool(10, object.isSynced);
        fbb.addInt64(11, object.pendingAction);
        fbb.addBool(12, object.isDeleted);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final toValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          18,
        );
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final fromParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0),
        );
        final userIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final isOccuringFlagParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          14,
          false,
        );
        final selectedPersonIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final toParam = toValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(toValue);
        final remoteIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0),
        );
        final isSyncedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          24,
          false,
        );
        final isDeletedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          28,
          false,
        );
        final pendingActionParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          26,
          0,
        );
        final object = GoodHabitEntity(
          id: idParam,
          from: fromParam,
          userId: userIdParam,
          name: nameParam,
          description: descriptionParam,
          isOccuringFlag: isOccuringFlagParam,
          selectedPersonId: selectedPersonIdParam,
          to: toParam,
          remoteId: remoteIdParam,
          updatedAt: updatedAtParam,
          isSynced: isSyncedParam,
          isDeleted: isDeletedParam,
          pendingAction: pendingActionParam,
        );

        return object;
      },
    ),
    SelectedPersonEntity: obx_int.EntityDefinition<SelectedPersonEntity>(
      model: _entities[4],
      toOneRelations: (SelectedPersonEntity object) => [],
      toManyRelations: (SelectedPersonEntity object) => {},
      getId: (SelectedPersonEntity object) => object.id,
      setId: (SelectedPersonEntity object, int id) {
        object.id = id;
      },
      objectToFB: (SelectedPersonEntity object, fb.Builder fbb) {
        final userIdOffset = fbb.writeString(object.userId);
        final nameOffset = fbb.writeString(object.name);
        final remoteIdOffset = object.remoteId == null
            ? null
            : fbb.writeString(object.remoteId!);
        fbb.startTable(10);
        fbb.addInt64(0, object.id);
        fbb.addBool(1, object.isSelected);
        fbb.addOffset(2, userIdOffset);
        fbb.addOffset(3, nameOffset);
        fbb.addOffset(4, remoteIdOffset);
        fbb.addInt64(5, object.updatedAt.millisecondsSinceEpoch);
        fbb.addBool(6, object.isSynced);
        fbb.addInt64(7, object.pendingAction);
        fbb.addBool(8, object.isDeleted);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final userIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final isSelectedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          6,
          false,
        );
        final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0),
        );
        final isSyncedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          16,
          false,
        );
        final isDeletedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          20,
          false,
        );
        final pendingActionParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final remoteIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final object = SelectedPersonEntity(
          id: idParam,
          userId: userIdParam,
          name: nameParam,
          isSelected: isSelectedParam,
          updatedAt: updatedAtParam,
          isSynced: isSyncedParam,
          isDeleted: isDeletedParam,
          pendingAction: pendingActionParam,
          remoteId: remoteIdParam,
        );

        return object;
      },
    ),
    UserCardEntity: obx_int.EntityDefinition<UserCardEntity>(
      model: _entities[5],
      toOneRelations: (UserCardEntity object) => [],
      toManyRelations: (UserCardEntity object) => {},
      getId: (UserCardEntity object) => object.id,
      setId: (UserCardEntity object, int id) {
        object.id = id;
      },
      objectToFB: (UserCardEntity object, fb.Builder fbb) {
        final userIdOffset = fbb.writeString(object.userId);
        final localImgPathOffset = fbb.writeString(object.localImgPath);
        final namesJsonOffset = fbb.writeString(object.namesJson);
        final remoteIdOffset = object.remoteId == null
            ? null
            : fbb.writeString(object.remoteId!);
        final remoteImgPathOffset = object.remoteImgPath == null
            ? null
            : fbb.writeString(object.remoteImgPath!);
        fbb.startTable(13);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.arasaacId);
        fbb.addOffset(2, userIdOffset);
        fbb.addOffset(3, localImgPathOffset);
        fbb.addOffset(4, namesJsonOffset);
        fbb.addOffset(5, remoteIdOffset);
        fbb.addInt64(6, object.updatedAt.millisecondsSinceEpoch);
        fbb.addBool(7, object.isSynced);
        fbb.addInt64(8, object.pendingAction);
        fbb.addBool(9, object.isDeleted);
        fbb.addOffset(10, remoteImgPathOffset);
        fbb.addInt64(11, object.wordCategory);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final arasaacIdParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          6,
        );
        final userIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final localImgPathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final namesJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final remoteIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0),
        );
        final isSyncedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          18,
          false,
        );
        final isDeletedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          22,
          false,
        );
        final pendingActionParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        final remoteImgPathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 24);
        final wordCategoryParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          26,
        );
        final object = UserCardEntity(
          id: idParam,
          arasaacId: arasaacIdParam,
          userId: userIdParam,
          localImgPath: localImgPathParam,
          namesJson: namesJsonParam,
          remoteId: remoteIdParam,
          updatedAt: updatedAtParam,
          isSynced: isSyncedParam,
          isDeleted: isDeletedParam,
          pendingAction: pendingActionParam,
          remoteImgPath: remoteImgPathParam,
          wordCategory: wordCategoryParam,
        );

        return object;
      },
    ),
    FirstThenBoardEntity: obx_int.EntityDefinition<FirstThenBoardEntity>(
      model: _entities[6],
      toOneRelations: (FirstThenBoardEntity object) => [
        object.first,
        object.then,
      ],
      toManyRelations: (FirstThenBoardEntity object) => {},
      getId: (FirstThenBoardEntity object) => object.id,
      setId: (FirstThenBoardEntity object, int id) {
        object.id = id;
      },
      objectToFB: (FirstThenBoardEntity object, fb.Builder fbb) {
        final userIdOffset = fbb.writeString(object.userId);
        final nameOffset = fbb.writeString(object.name);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, userIdOffset);
        fbb.addInt64(2, object.first.targetId);
        fbb.addInt64(3, object.then.targetId);
        fbb.addOffset(4, nameOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final userIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final firstParam = obx.ToOne<UserCardEntity>(
          targetId: const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
        );
        final thenParam = obx.ToOne<UserCardEntity>(
          targetId: const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final object = FirstThenBoardEntity(
          id: idParam,
          userId: userIdParam,
          first: firstParam,
          then: thenParam,
          name: nameParam,
        );
        object.first.attach(store);
        object.then.attach(store);
        return object;
      },
    ),
    VisualListEntity: obx_int.EntityDefinition<VisualListEntity>(
      model: _entities[7],
      toOneRelations: (VisualListEntity object) => [],
      toManyRelations: (VisualListEntity object) => {
        obx_int.RelInfo<VisualListEntity>.toMany(1, object.id): object.steps,
      },
      getId: (VisualListEntity object) => object.id,
      setId: (VisualListEntity object, int id) {
        object.id = id;
      },
      objectToFB: (VisualListEntity object, fb.Builder fbb) {
        final userIdOffset = fbb.writeString(object.userId);
        final nameOffset = fbb.writeString(object.name);
        final stepsOrderJsonOffset = object.stepsOrderJson == null
            ? null
            : fbb.writeString(object.stepsOrderJson!);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, userIdOffset);
        fbb.addOffset(2, nameOffset);
        fbb.addBool(3, object.isVisualSchedule);
        fbb.addBool(4, object.isVisualDiagram);
        fbb.addOffset(5, stepsOrderJsonOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final userIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final isVisualScheduleParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          10,
          false,
        );
        final isVisualDiagramParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          12,
          false,
        );
        final stepsOrderJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final object = VisualListEntity(
          id: idParam,
          userId: userIdParam,
          name: nameParam,
          isVisualSchedule: isVisualScheduleParam,
          isVisualDiagram: isVisualDiagramParam,
          stepsOrderJson: stepsOrderJsonParam,
        );
        obx_int.InternalToManyAccess.setRelInfo<VisualListEntity>(
          object.steps,
          store,
          obx_int.RelInfo<VisualListEntity>.toMany(1, object.id),
        );
        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [ChallengingBehaviourDiaryEntryEntity] entity fields to define ObjectBox queries.
class ChallengingBehaviourDiaryEntryEntity_ {
  /// See [ChallengingBehaviourDiaryEntryEntity.id].
  static final id =
      obx.QueryIntegerProperty<ChallengingBehaviourDiaryEntryEntity>(
        _entities[0].properties[0],
      );

  /// See [ChallengingBehaviourDiaryEntryEntity.challengingBehaviour].
  static final challengingBehaviour =
      obx.QueryRelationToOne<
        ChallengingBehaviourDiaryEntryEntity,
        ChallengingBehaviourEntity
      >(_entities[0].properties[1]);

  /// See [ChallengingBehaviourDiaryEntryEntity.location].
  static final location =
      obx.QueryStringProperty<ChallengingBehaviourDiaryEntryEntity>(
        _entities[0].properties[2],
      );

  /// See [ChallengingBehaviourDiaryEntryEntity.date].
  static final date =
      obx.QueryDateProperty<ChallengingBehaviourDiaryEntryEntity>(
        _entities[0].properties[3],
      );

  /// See [ChallengingBehaviourDiaryEntryEntity.duration].
  static final duration =
      obx.QueryIntegerProperty<ChallengingBehaviourDiaryEntryEntity>(
        _entities[0].properties[4],
      );

  /// See [ChallengingBehaviourDiaryEntryEntity.circumstances].
  static final circumstances =
      obx.QueryStringProperty<ChallengingBehaviourDiaryEntryEntity>(
        _entities[0].properties[5],
      );

  /// See [ChallengingBehaviourDiaryEntryEntity.people].
  static final people =
      obx.QueryStringVectorProperty<ChallengingBehaviourDiaryEntryEntity>(
        _entities[0].properties[6],
      );

  /// See [ChallengingBehaviourDiaryEntryEntity.outcome].
  static final outcome =
      obx.QueryStringProperty<ChallengingBehaviourDiaryEntryEntity>(
        _entities[0].properties[7],
      );

  /// See [ChallengingBehaviourDiaryEntryEntity.reflection].
  static final reflection =
      obx.QueryStringProperty<ChallengingBehaviourDiaryEntryEntity>(
        _entities[0].properties[8],
      );
}

/// [ChallengingBehaviourEntity] entity fields to define ObjectBox queries.
class ChallengingBehaviourEntity_ {
  /// See [ChallengingBehaviourEntity.id].
  static final id = obx.QueryIntegerProperty<ChallengingBehaviourEntity>(
    _entities[1].properties[0],
  );

  /// See [ChallengingBehaviourEntity.occuring].
  static final occuring = obx.QueryBooleanProperty<ChallengingBehaviourEntity>(
    _entities[1].properties[1],
  );

  /// See [ChallengingBehaviourEntity.name].
  static final name = obx.QueryStringProperty<ChallengingBehaviourEntity>(
    _entities[1].properties[2],
  );

  /// See [ChallengingBehaviourEntity.from].
  static final from = obx.QueryDateProperty<ChallengingBehaviourEntity>(
    _entities[1].properties[3],
  );

  /// See [ChallengingBehaviourEntity.generalDescription].
  static final generalDescription =
      obx.QueryStringProperty<ChallengingBehaviourEntity>(
        _entities[1].properties[4],
      );

  /// See [ChallengingBehaviourEntity.userId].
  static final userId = obx.QueryStringProperty<ChallengingBehaviourEntity>(
    _entities[1].properties[5],
  );

  /// See [ChallengingBehaviourEntity.selectedPersonId].
  static final selectedPersonId =
      obx.QueryIntegerProperty<ChallengingBehaviourEntity>(
        _entities[1].properties[6],
      );

  /// See [ChallengingBehaviourEntity.remoteId].
  static final remoteId = obx.QueryStringProperty<ChallengingBehaviourEntity>(
    _entities[1].properties[7],
  );

  /// See [ChallengingBehaviourEntity.updatedAt].
  static final updatedAt = obx.QueryDateProperty<ChallengingBehaviourEntity>(
    _entities[1].properties[8],
  );

  /// See [ChallengingBehaviourEntity.isSynced].
  static final isSynced = obx.QueryBooleanProperty<ChallengingBehaviourEntity>(
    _entities[1].properties[9],
  );

  /// See [ChallengingBehaviourEntity.pendingAction].
  static final pendingAction =
      obx.QueryIntegerProperty<ChallengingBehaviourEntity>(
        _entities[1].properties[10],
      );

  /// See [ChallengingBehaviourEntity.isDeleted].
  static final isDeleted = obx.QueryBooleanProperty<ChallengingBehaviourEntity>(
    _entities[1].properties[11],
  );

  /// see [ChallengingBehaviourEntity.diaryEntries]
  static final diaryEntries =
      obx.QueryBacklinkToMany<
        ChallengingBehaviourDiaryEntryEntity,
        ChallengingBehaviourEntity
      >(ChallengingBehaviourDiaryEntryEntity_.challengingBehaviour);
}

/// [EatingHabitEntity] entity fields to define ObjectBox queries.
class EatingHabitEntity_ {
  /// See [EatingHabitEntity.id].
  static final id = obx.QueryIntegerProperty<EatingHabitEntity>(
    _entities[2].properties[0],
  );

  /// See [EatingHabitEntity.to].
  static final to = obx.QueryDateProperty<EatingHabitEntity>(
    _entities[2].properties[1],
  );

  /// See [EatingHabitEntity.isEatingFlag].
  static final isEatingFlag = obx.QueryBooleanProperty<EatingHabitEntity>(
    _entities[2].properties[2],
  );

  /// See [EatingHabitEntity.from].
  static final from = obx.QueryDateProperty<EatingHabitEntity>(
    _entities[2].properties[3],
  );

  /// See [EatingHabitEntity.name].
  static final name = obx.QueryStringProperty<EatingHabitEntity>(
    _entities[2].properties[4],
  );

  /// See [EatingHabitEntity.description].
  static final description = obx.QueryStringProperty<EatingHabitEntity>(
    _entities[2].properties[5],
  );

  /// See [EatingHabitEntity.userId].
  static final userId = obx.QueryStringProperty<EatingHabitEntity>(
    _entities[2].properties[6],
  );

  /// See [EatingHabitEntity.selectedPersonId].
  static final selectedPersonId = obx.QueryIntegerProperty<EatingHabitEntity>(
    _entities[2].properties[7],
  );

  /// See [EatingHabitEntity.imageFilePath].
  static final imageFilePath = obx.QueryStringProperty<EatingHabitEntity>(
    _entities[2].properties[8],
  );

  /// See [EatingHabitEntity.remoteId].
  static final remoteId = obx.QueryStringProperty<EatingHabitEntity>(
    _entities[2].properties[9],
  );

  /// See [EatingHabitEntity.updatedAt].
  static final updatedAt = obx.QueryDateProperty<EatingHabitEntity>(
    _entities[2].properties[10],
  );

  /// See [EatingHabitEntity.isSynced].
  static final isSynced = obx.QueryBooleanProperty<EatingHabitEntity>(
    _entities[2].properties[11],
  );

  /// See [EatingHabitEntity.pendingAction].
  static final pendingAction = obx.QueryIntegerProperty<EatingHabitEntity>(
    _entities[2].properties[12],
  );

  /// See [EatingHabitEntity.isDeleted].
  static final isDeleted = obx.QueryBooleanProperty<EatingHabitEntity>(
    _entities[2].properties[13],
  );

  /// See [EatingHabitEntity.remoteImgPath].
  static final remoteImgPath = obx.QueryStringProperty<EatingHabitEntity>(
    _entities[2].properties[14],
  );
}

/// [GoodHabitEntity] entity fields to define ObjectBox queries.
class GoodHabitEntity_ {
  /// See [GoodHabitEntity.id].
  static final id = obx.QueryIntegerProperty<GoodHabitEntity>(
    _entities[3].properties[0],
  );

  /// See [GoodHabitEntity.from].
  static final from = obx.QueryDateProperty<GoodHabitEntity>(
    _entities[3].properties[1],
  );

  /// See [GoodHabitEntity.userId].
  static final userId = obx.QueryStringProperty<GoodHabitEntity>(
    _entities[3].properties[2],
  );

  /// See [GoodHabitEntity.name].
  static final name = obx.QueryStringProperty<GoodHabitEntity>(
    _entities[3].properties[3],
  );

  /// See [GoodHabitEntity.description].
  static final description = obx.QueryStringProperty<GoodHabitEntity>(
    _entities[3].properties[4],
  );

  /// See [GoodHabitEntity.isOccuringFlag].
  static final isOccuringFlag = obx.QueryBooleanProperty<GoodHabitEntity>(
    _entities[3].properties[5],
  );

  /// See [GoodHabitEntity.selectedPersonId].
  static final selectedPersonId = obx.QueryIntegerProperty<GoodHabitEntity>(
    _entities[3].properties[6],
  );

  /// See [GoodHabitEntity.to].
  static final to = obx.QueryDateProperty<GoodHabitEntity>(
    _entities[3].properties[7],
  );

  /// See [GoodHabitEntity.remoteId].
  static final remoteId = obx.QueryStringProperty<GoodHabitEntity>(
    _entities[3].properties[8],
  );

  /// See [GoodHabitEntity.updatedAt].
  static final updatedAt = obx.QueryDateProperty<GoodHabitEntity>(
    _entities[3].properties[9],
  );

  /// See [GoodHabitEntity.isSynced].
  static final isSynced = obx.QueryBooleanProperty<GoodHabitEntity>(
    _entities[3].properties[10],
  );

  /// See [GoodHabitEntity.pendingAction].
  static final pendingAction = obx.QueryIntegerProperty<GoodHabitEntity>(
    _entities[3].properties[11],
  );

  /// See [GoodHabitEntity.isDeleted].
  static final isDeleted = obx.QueryBooleanProperty<GoodHabitEntity>(
    _entities[3].properties[12],
  );
}

/// [SelectedPersonEntity] entity fields to define ObjectBox queries.
class SelectedPersonEntity_ {
  /// See [SelectedPersonEntity.id].
  static final id = obx.QueryIntegerProperty<SelectedPersonEntity>(
    _entities[4].properties[0],
  );

  /// See [SelectedPersonEntity.isSelected].
  static final isSelected = obx.QueryBooleanProperty<SelectedPersonEntity>(
    _entities[4].properties[1],
  );

  /// See [SelectedPersonEntity.userId].
  static final userId = obx.QueryStringProperty<SelectedPersonEntity>(
    _entities[4].properties[2],
  );

  /// See [SelectedPersonEntity.name].
  static final name = obx.QueryStringProperty<SelectedPersonEntity>(
    _entities[4].properties[3],
  );

  /// See [SelectedPersonEntity.remoteId].
  static final remoteId = obx.QueryStringProperty<SelectedPersonEntity>(
    _entities[4].properties[4],
  );

  /// See [SelectedPersonEntity.updatedAt].
  static final updatedAt = obx.QueryDateProperty<SelectedPersonEntity>(
    _entities[4].properties[5],
  );

  /// See [SelectedPersonEntity.isSynced].
  static final isSynced = obx.QueryBooleanProperty<SelectedPersonEntity>(
    _entities[4].properties[6],
  );

  /// See [SelectedPersonEntity.pendingAction].
  static final pendingAction = obx.QueryIntegerProperty<SelectedPersonEntity>(
    _entities[4].properties[7],
  );

  /// See [SelectedPersonEntity.isDeleted].
  static final isDeleted = obx.QueryBooleanProperty<SelectedPersonEntity>(
    _entities[4].properties[8],
  );
}

/// [UserCardEntity] entity fields to define ObjectBox queries.
class UserCardEntity_ {
  /// See [UserCardEntity.id].
  static final id = obx.QueryIntegerProperty<UserCardEntity>(
    _entities[5].properties[0],
  );

  /// See [UserCardEntity.arasaacId].
  static final arasaacId = obx.QueryIntegerProperty<UserCardEntity>(
    _entities[5].properties[1],
  );

  /// See [UserCardEntity.userId].
  static final userId = obx.QueryStringProperty<UserCardEntity>(
    _entities[5].properties[2],
  );

  /// See [UserCardEntity.localImgPath].
  static final localImgPath = obx.QueryStringProperty<UserCardEntity>(
    _entities[5].properties[3],
  );

  /// See [UserCardEntity.namesJson].
  static final namesJson = obx.QueryStringProperty<UserCardEntity>(
    _entities[5].properties[4],
  );

  /// See [UserCardEntity.remoteId].
  static final remoteId = obx.QueryStringProperty<UserCardEntity>(
    _entities[5].properties[5],
  );

  /// See [UserCardEntity.updatedAt].
  static final updatedAt = obx.QueryDateProperty<UserCardEntity>(
    _entities[5].properties[6],
  );

  /// See [UserCardEntity.isSynced].
  static final isSynced = obx.QueryBooleanProperty<UserCardEntity>(
    _entities[5].properties[7],
  );

  /// See [UserCardEntity.pendingAction].
  static final pendingAction = obx.QueryIntegerProperty<UserCardEntity>(
    _entities[5].properties[8],
  );

  /// See [UserCardEntity.isDeleted].
  static final isDeleted = obx.QueryBooleanProperty<UserCardEntity>(
    _entities[5].properties[9],
  );

  /// See [UserCardEntity.remoteImgPath].
  static final remoteImgPath = obx.QueryStringProperty<UserCardEntity>(
    _entities[5].properties[10],
  );

  /// See [UserCardEntity.wordCategory].
  static final wordCategory = obx.QueryIntegerProperty<UserCardEntity>(
    _entities[5].properties[11],
  );
}

/// [FirstThenBoardEntity] entity fields to define ObjectBox queries.
class FirstThenBoardEntity_ {
  /// See [FirstThenBoardEntity.id].
  static final id = obx.QueryIntegerProperty<FirstThenBoardEntity>(
    _entities[6].properties[0],
  );

  /// See [FirstThenBoardEntity.userId].
  static final userId = obx.QueryStringProperty<FirstThenBoardEntity>(
    _entities[6].properties[1],
  );

  /// See [FirstThenBoardEntity.first].
  static final first =
      obx.QueryRelationToOne<FirstThenBoardEntity, UserCardEntity>(
        _entities[6].properties[2],
      );

  /// See [FirstThenBoardEntity.then].
  static final then =
      obx.QueryRelationToOne<FirstThenBoardEntity, UserCardEntity>(
        _entities[6].properties[3],
      );

  /// See [FirstThenBoardEntity.name].
  static final name = obx.QueryStringProperty<FirstThenBoardEntity>(
    _entities[6].properties[4],
  );
}

/// [VisualListEntity] entity fields to define ObjectBox queries.
class VisualListEntity_ {
  /// See [VisualListEntity.id].
  static final id = obx.QueryIntegerProperty<VisualListEntity>(
    _entities[7].properties[0],
  );

  /// See [VisualListEntity.userId].
  static final userId = obx.QueryStringProperty<VisualListEntity>(
    _entities[7].properties[1],
  );

  /// See [VisualListEntity.name].
  static final name = obx.QueryStringProperty<VisualListEntity>(
    _entities[7].properties[2],
  );

  /// See [VisualListEntity.isVisualSchedule].
  static final isVisualSchedule = obx.QueryBooleanProperty<VisualListEntity>(
    _entities[7].properties[3],
  );

  /// See [VisualListEntity.isVisualDiagram].
  static final isVisualDiagram = obx.QueryBooleanProperty<VisualListEntity>(
    _entities[7].properties[4],
  );

  /// See [VisualListEntity.stepsOrderJson].
  static final stepsOrderJson = obx.QueryStringProperty<VisualListEntity>(
    _entities[7].properties[5],
  );

  /// see [VisualListEntity.steps]
  static final steps =
      obx.QueryRelationToMany<VisualListEntity, UserCardEntity>(
        _entities[7].relations[0],
      );
}
