// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'features/challenging_behaviour/data/model/challenging_behaviour_diary_entry_entity.dart';
import 'features/challenging_behaviour/data/model/challenging_behaviour_entity.dart';
import 'features/eating_habits/data/model/eating_habit_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 1777307641083598478),
    name: 'EatingHabitEntity',
    lastPropertyId: const obx_int.IdUid(7, 4128286833958398028),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7323305404545168403),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1219579721037450855),
        name: 'from',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 593779817146309026),
        name: 'to',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1176311604953178663),
        name: 'isEatingFlag',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3518344782468400788),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4393786231541083778),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 4128286833958398028),
        name: 'userId',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 139465113525671056),
    name: 'ChallengingBehaviourDiaryEntryEntity',
    lastPropertyId: const obx_int.IdUid(9, 8473330541405588167),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3276799885575513242),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1996232934584247842),
        name: 'challengingBehaviourId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(1, 7265063553320486894),
        relationTarget: 'ChallengingBehaviourEntity',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3810550962242010286),
        name: 'location',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4327789277245649275),
        name: 'date',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2257877021023419224),
        name: 'duration',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5067823526267149243),
        name: 'circumstances',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 6317075041900276104),
        name: 'people',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 9114528613422825857),
        name: 'outcome',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 8473330541405588167),
        name: 'reflection',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 6112168635049409585),
    name: 'ChallengingBehaviourEntity',
    lastPropertyId: const obx_int.IdUid(6, 938737596790947008),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5353683167311258387),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 69716348719230726),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1233996314118088075),
        name: 'from',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 591679213236383350),
        name: 'generalDescription',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6645588857862198462),
        name: 'occuring',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 938737596790947008),
        name: 'userId',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'diaryEntries',
        srcEntity: 'ChallengingBehaviourDiaryEntryEntity',
        srcField: '',
      ),
    ],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(3, 6112168635049409585),
    lastIndexId: const obx_int.IdUid(1, 7265063553320486894),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    EatingHabitEntity: obx_int.EntityDefinition<EatingHabitEntity>(
      model: _entities[0],
      toOneRelations: (EatingHabitEntity object) => [],
      toManyRelations: (EatingHabitEntity object) => {},
      getId: (EatingHabitEntity object) => object.id,
      setId: (EatingHabitEntity object, int id) {
        object.id = id;
      },
      objectToFB: (EatingHabitEntity object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final descriptionOffset = fbb.writeString(object.description);
        final userIdOffset = fbb.writeString(object.userId);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.from.millisecondsSinceEpoch);
        fbb.addInt64(2, object.to?.millisecondsSinceEpoch);
        fbb.addBool(3, object.isEatingFlag);
        fbb.addOffset(4, nameOffset);
        fbb.addOffset(5, descriptionOffset);
        fbb.addOffset(6, userIdOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final toValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          8,
        );
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final fromParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0),
        );
        final toParam = toValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(toValue);
        final isEatingFlagParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          10,
          false,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final userIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final object = EatingHabitEntity(
          id: idParam,
          from: fromParam,
          to: toParam,
          isEatingFlag: isEatingFlagParam,
          name: nameParam,
          description: descriptionParam,
          userId: userIdParam,
        );

        return object;
      },
    ),
    ChallengingBehaviourDiaryEntryEntity:
        obx_int.EntityDefinition<ChallengingBehaviourDiaryEntryEntity>(
          model: _entities[1],
          toOneRelations: (ChallengingBehaviourDiaryEntryEntity object) => [
            object.challengingBehaviour,
          ],
          toManyRelations: (ChallengingBehaviourDiaryEntryEntity object) => {},
          getId: (ChallengingBehaviourDiaryEntryEntity object) => object.id,
          setId: (ChallengingBehaviourDiaryEntryEntity object, int id) {
            object.id = id;
          },
          objectToFB:
              (ChallengingBehaviourDiaryEntryEntity object, fb.Builder fbb) {
                final locationOffset = fbb.writeString(object.location);
                final circumstancesOffset = fbb.writeString(
                  object.circumstances,
                );
                final peopleOffset = fbb.writeList(
                  object.people.map(fbb.writeString).toList(growable: false),
                );
                final outcomeOffset = fbb.writeString(object.outcome);
                final reflectionOffset = fbb.writeString(object.reflection);
                fbb.startTable(10);
                fbb.addInt64(0, object.id ?? 0);
                fbb.addInt64(1, object.challengingBehaviour.targetId);
                fbb.addOffset(2, locationOffset);
                fbb.addInt64(3, object.date.millisecondsSinceEpoch);
                fbb.addInt64(4, object.duration);
                fbb.addOffset(5, circumstancesOffset);
                fbb.addOffset(6, peopleOffset);
                fbb.addOffset(7, outcomeOffset);
                fbb.addOffset(8, reflectionOffset);
                fbb.finish(fbb.endTable());
                return object.id ?? 0;
              },
          objectFromFB: (obx.Store store, ByteData fbData) {
            final buffer = fb.BufferContext(fbData);
            final rootOffset = buffer.derefObject(0);
            final idParam = const fb.Int64Reader().vTableGetNullable(
              buffer,
              rootOffset,
              4,
            );
            final locationParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGet(buffer, rootOffset, 8, '');
            final dateParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
            );
            final durationParam = const fb.Int64Reader().vTableGet(
              buffer,
              rootOffset,
              12,
              0,
            );
            final circumstancesParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGet(buffer, rootOffset, 14, '');
            final peopleParam = const fb.ListReader<String>(
              fb.StringReader(asciiOptimization: true),
              lazy: false,
            ).vTableGet(buffer, rootOffset, 16, []);
            final outcomeParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGet(buffer, rootOffset, 18, '');
            final reflectionParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGet(buffer, rootOffset, 20, '');
            final object = ChallengingBehaviourDiaryEntryEntity(
              id: idParam,
              location: locationParam,
              date: dateParam,
              duration: durationParam,
              circumstances: circumstancesParam,
              people: peopleParam,
              outcome: outcomeParam,
              reflection: reflectionParam,
            );
            object.challengingBehaviour.targetId = const fb.Int64Reader()
                .vTableGet(buffer, rootOffset, 6, 0);
            object.challengingBehaviour.attach(store);
            return object;
          },
        ),
    ChallengingBehaviourEntity:
        obx_int.EntityDefinition<ChallengingBehaviourEntity>(
          model: _entities[2],
          toOneRelations: (ChallengingBehaviourEntity object) => [],
          toManyRelations: (ChallengingBehaviourEntity object) => {
            obx_int.RelInfo<ChallengingBehaviourDiaryEntryEntity>.toOneBacklink(
              2,
              object.id!,
              (ChallengingBehaviourDiaryEntryEntity srcObject) =>
                  srcObject.challengingBehaviour,
            ): object.diaryEntries,
          },
          getId: (ChallengingBehaviourEntity object) => object.id,
          setId: (ChallengingBehaviourEntity object, int id) {
            object.id = id;
          },
          objectToFB: (ChallengingBehaviourEntity object, fb.Builder fbb) {
            final nameOffset = fbb.writeString(object.name);
            final generalDescriptionOffset = fbb.writeString(
              object.generalDescription,
            );
            final userIdOffset = fbb.writeString(object.userId);
            fbb.startTable(7);
            fbb.addInt64(0, object.id ?? 0);
            fbb.addOffset(1, nameOffset);
            fbb.addInt64(2, object.from.millisecondsSinceEpoch);
            fbb.addOffset(3, generalDescriptionOffset);
            fbb.addBool(4, object.occuring);
            fbb.addOffset(5, userIdOffset);
            fbb.finish(fbb.endTable());
            return object.id ?? 0;
          },
          objectFromFB: (obx.Store store, ByteData fbData) {
            final buffer = fb.BufferContext(fbData);
            final rootOffset = buffer.derefObject(0);
            final idParam = const fb.Int64Reader().vTableGetNullable(
              buffer,
              rootOffset,
              4,
            );
            final nameParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGet(buffer, rootOffset, 6, '');
            final fromParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
            );
            final generalDescriptionParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGet(buffer, rootOffset, 10, '');
            final diaryEntriesParam =
                obx.ToMany<ChallengingBehaviourDiaryEntryEntity>();
            final occuringParam = const fb.BoolReader().vTableGet(
              buffer,
              rootOffset,
              12,
              false,
            );
            final userIdParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGet(buffer, rootOffset, 14, '');
            final object = ChallengingBehaviourEntity(
              id: idParam,
              name: nameParam,
              from: fromParam,
              generalDescription: generalDescriptionParam,
              diaryEntries: diaryEntriesParam,
              occuring: occuringParam,
              userId: userIdParam,
            );
            obx_int.InternalToManyAccess.setRelInfo<ChallengingBehaviourEntity>(
              object.diaryEntries,
              store,
              obx_int.RelInfo<
                ChallengingBehaviourDiaryEntryEntity
              >.toOneBacklink(
                2,
                object.id!,
                (ChallengingBehaviourDiaryEntryEntity srcObject) =>
                    srcObject.challengingBehaviour,
              ),
            );
            return object;
          },
        ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [EatingHabitEntity] entity fields to define ObjectBox queries.
class EatingHabitEntity_ {
  /// See [EatingHabitEntity.id].
  static final id = obx.QueryIntegerProperty<EatingHabitEntity>(
    _entities[0].properties[0],
  );

  /// See [EatingHabitEntity.from].
  static final from = obx.QueryDateProperty<EatingHabitEntity>(
    _entities[0].properties[1],
  );

  /// See [EatingHabitEntity.to].
  static final to = obx.QueryDateProperty<EatingHabitEntity>(
    _entities[0].properties[2],
  );

  /// See [EatingHabitEntity.isEatingFlag].
  static final isEatingFlag = obx.QueryBooleanProperty<EatingHabitEntity>(
    _entities[0].properties[3],
  );

  /// See [EatingHabitEntity.name].
  static final name = obx.QueryStringProperty<EatingHabitEntity>(
    _entities[0].properties[4],
  );

  /// See [EatingHabitEntity.description].
  static final description = obx.QueryStringProperty<EatingHabitEntity>(
    _entities[0].properties[5],
  );

  /// See [EatingHabitEntity.userId].
  static final userId = obx.QueryStringProperty<EatingHabitEntity>(
    _entities[0].properties[6],
  );
}

/// [ChallengingBehaviourDiaryEntryEntity] entity fields to define ObjectBox queries.
class ChallengingBehaviourDiaryEntryEntity_ {
  /// See [ChallengingBehaviourDiaryEntryEntity.id].
  static final id =
      obx.QueryIntegerProperty<ChallengingBehaviourDiaryEntryEntity>(
        _entities[1].properties[0],
      );

  /// See [ChallengingBehaviourDiaryEntryEntity.challengingBehaviour].
  static final challengingBehaviour =
      obx.QueryRelationToOne<
        ChallengingBehaviourDiaryEntryEntity,
        ChallengingBehaviourEntity
      >(_entities[1].properties[1]);

  /// See [ChallengingBehaviourDiaryEntryEntity.location].
  static final location =
      obx.QueryStringProperty<ChallengingBehaviourDiaryEntryEntity>(
        _entities[1].properties[2],
      );

  /// See [ChallengingBehaviourDiaryEntryEntity.date].
  static final date =
      obx.QueryDateProperty<ChallengingBehaviourDiaryEntryEntity>(
        _entities[1].properties[3],
      );

  /// See [ChallengingBehaviourDiaryEntryEntity.duration].
  static final duration =
      obx.QueryIntegerProperty<ChallengingBehaviourDiaryEntryEntity>(
        _entities[1].properties[4],
      );

  /// See [ChallengingBehaviourDiaryEntryEntity.circumstances].
  static final circumstances =
      obx.QueryStringProperty<ChallengingBehaviourDiaryEntryEntity>(
        _entities[1].properties[5],
      );

  /// See [ChallengingBehaviourDiaryEntryEntity.people].
  static final people =
      obx.QueryStringVectorProperty<ChallengingBehaviourDiaryEntryEntity>(
        _entities[1].properties[6],
      );

  /// See [ChallengingBehaviourDiaryEntryEntity.outcome].
  static final outcome =
      obx.QueryStringProperty<ChallengingBehaviourDiaryEntryEntity>(
        _entities[1].properties[7],
      );

  /// See [ChallengingBehaviourDiaryEntryEntity.reflection].
  static final reflection =
      obx.QueryStringProperty<ChallengingBehaviourDiaryEntryEntity>(
        _entities[1].properties[8],
      );
}

/// [ChallengingBehaviourEntity] entity fields to define ObjectBox queries.
class ChallengingBehaviourEntity_ {
  /// See [ChallengingBehaviourEntity.id].
  static final id = obx.QueryIntegerProperty<ChallengingBehaviourEntity>(
    _entities[2].properties[0],
  );

  /// See [ChallengingBehaviourEntity.name].
  static final name = obx.QueryStringProperty<ChallengingBehaviourEntity>(
    _entities[2].properties[1],
  );

  /// See [ChallengingBehaviourEntity.from].
  static final from = obx.QueryDateProperty<ChallengingBehaviourEntity>(
    _entities[2].properties[2],
  );

  /// See [ChallengingBehaviourEntity.generalDescription].
  static final generalDescription =
      obx.QueryStringProperty<ChallengingBehaviourEntity>(
        _entities[2].properties[3],
      );

  /// See [ChallengingBehaviourEntity.occuring].
  static final occuring = obx.QueryBooleanProperty<ChallengingBehaviourEntity>(
    _entities[2].properties[4],
  );

  /// See [ChallengingBehaviourEntity.userId].
  static final userId = obx.QueryStringProperty<ChallengingBehaviourEntity>(
    _entities[2].properties[5],
  );

  /// see [ChallengingBehaviourEntity.diaryEntries]
  static final diaryEntries =
      obx.QueryBacklinkToMany<
        ChallengingBehaviourDiaryEntryEntity,
        ChallengingBehaviourEntity
      >(ChallengingBehaviourDiaryEntryEntity_.challengingBehaviour);
}
